from .evm_smart_wallet import evm_smart_wallet_factory
from .solana_smart_wallet_factory import solana_smart_wallet_factory

# Export factory functions
evm_wallet_factory = evm_smart_wallet_factory
solana_wallet_factory = solana_smart_wallet_factory
